# utils/file_writer.py
import json
import os
import logging
from typing import Dict, Any, List, Union
from datetime import datetime
from utils.pydantic_compat import model_to_dict
from schemas.output_models import PodcastContentPackage

logger = logging.getLogger("podcast_production.file_writer")

class FileWriter:
    """
    Utility class for writing podcast content to multiple file formats.
    Handles both PodcastContentPackage (Pydantic model) and legacy compatibility objects.
    """

    def __init__(self, base_output_dir: str = "output"):
        self.base_output_dir = base_output_dir
        self.logger = logger
        os.makedirs(self.base_output_dir, exist_ok=True)

    def write_podcast_package(self, content_package: Union[PodcastContentPackage, Any]) -> str:
        """
        Write the complete podcast package to multiple file formats and consolidated JSON.
        Accepts a PodcastContentPackage Pydantic model (preferred) or a legacy compatibility object.
        Returns the path to the main package directory.
        """
        try:
            # Normalize to Pydantic-like structure / dict accessors
            meta = getattr(content_package, "metadata", None)

            # topic resolution
            topic = None
            if meta is not None:
                # metadata may be a pydantic model or a dict-like object
                if hasattr(meta, "refined_topic"):
                    topic = getattr(meta, "refined_topic", None) or getattr(meta, "topic", None)
                elif isinstance(meta, dict):
                    topic = meta.get("refined_topic") or meta.get("topic")
            # final fallback
            topic = topic or getattr(content_package, "topic", None) or "untitled"

            safe_topic = self._sanitize_filename(topic)
            package_dir = os.path.join(self.base_output_dir, safe_topic)
            os.makedirs(package_dir, exist_ok=True)

            self.logger.info(f"Writing podcast package to: {package_dir}")

            # Script & show notes
            script_text = getattr(content_package, "script", "") or ""
            show_notes_text = getattr(content_package, "show_notes", "") or ""
            self._write_script_file(package_dir, script_text, topic)
            self._write_show_notes_file(package_dir, show_notes_text)

            # Social posts - accept Pydantic model or dict
            social_posts_raw = getattr(content_package, "social_media_posts", {}) or {}
            if hasattr(social_posts_raw, "model_dump"):
                try:
                    social_posts = social_posts_raw.model_dump()
                except Exception:
                    social_posts = model_to_dict(social_posts_raw)
            elif isinstance(social_posts_raw, dict):
                social_posts = social_posts_raw
            else:
                # last resort, try model_to_dict which handles many Pydantic/datatypes
                try:
                    social_posts = model_to_dict(social_posts_raw)
                except Exception:
                    # make a safely serializable dict
                    social_posts = {}
            self._write_social_posts_file(package_dir, social_posts)

            # Sources list
            all_sources = getattr(content_package, "all_sources", []) or []
            # If an inner Pydantic model stored sources under research_materials, attempt to extract urls
            if not all_sources and getattr(content_package, "research_materials", None):
                try:
                    rms = getattr(content_package, "research_materials")
                    # research_materials could be a list of Pydantic models or dicts
                    all_sources = [getattr(r, "url", None) or (r.get("url") if isinstance(r, dict) else None) for r in rms]
                    all_sources = [u for u in all_sources if u]
                except Exception:
                    all_sources = []

            self._write_sources_file(package_dir, all_sources)

            # Citations file (new)
            self._write_citations_file(package_dir, content_package)

            # Metadata file
            self._write_metadata_file(package_dir, content_package)

            # Consolidated JSON
            consolidated_path = self._write_consolidated_json(package_dir, content_package)

            self.logger.info(f"Podcast package successfully written to: {package_dir}")
            return package_dir

        except Exception as e:
            self.logger.error(f"Error writing podcast package: {str(e)}", exc_info=True)
            raise

    def _write_script_file(self, package_dir: str, script: str, topic: str) -> None:
        script_path = os.path.join(package_dir, "script.md")

        script_content = f"""# Podcast Script: {topic}

## Script Content

{script}

---
*Generated by AI Podcast Production Suite on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(script_content)

        self.logger.debug(f"Script written to: {script_path}")

    def _write_show_notes_file(self, package_dir: str, show_notes: str) -> None:
        show_notes_path = os.path.join(package_dir, "show_notes.md")

        show_notes_content = f"""# Podcast Show Notes

{show_notes}

--- 
*Generated by AI Podcast Production Suite on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        with open(show_notes_path, 'w', encoding='utf-8') as f:
            f.write(show_notes_content)

        self.logger.debug(f"Show notes written to: {show_notes_path}")

    def _write_social_posts_file(self, package_dir: str, social_posts: Dict[str, List[str]]) -> None:
        social_path = os.path.join(package_dir, "social_posts.json")

        social_content = {
            "generated_at": datetime.now().isoformat(),
            "platforms": social_posts
        }

        with open(social_path, 'w', encoding='utf-8') as f:
            json.dump(social_content, f, indent=2, ensure_ascii=False)

        self.logger.debug(f"Social posts written to: {social_path}")

    def _write_sources_file(self, package_dir: str, sources: List[str]) -> None:
        sources_path = os.path.join(package_dir, "sources.json")

        sources_content = {
            "generated_at": datetime.now().isoformat(),
            "total_sources": len(sources),
            "sources": sources
        }

        with open(sources_path, 'w', encoding='utf-8') as f:
            json.dump(sources_content, f, indent=2, ensure_ascii=False)

        self.logger.debug(f"Sources written to: {sources_path} ({len(sources)} sources)")

    def _write_citations_file(self, package_dir: str, content_package: PodcastContentPackage) -> None:
        """Write detailed citations file with academic formatting."""
        citations_path = os.path.join(package_dir, "citations.json")
        citations_md_path = os.path.join(package_dir, "citations.md")
        
        # Get citations data from content package
        citations_data = getattr(content_package, "citations_data", None)
        
        if citations_data:
            # Write JSON format
            with open(citations_path, 'w', encoding='utf-8') as f:
                json.dump(citations_data, f, indent=2, ensure_ascii=False)
            
            # Write Markdown format with formatted bibliography
            md_content = self._format_citations_markdown(citations_data)
            with open(citations_md_path, 'w', encoding='utf-8') as f:
                f.write(md_content)
            
            self.logger.debug(f"Citations written to: {citations_path} and {citations_md_path}")
        else:
            self.logger.debug("No citations data available")
    
    def _format_citations_markdown(self, citations_data: Dict[str, Any]) -> str:
        """Format citations data as markdown."""
        lines = ["# Citations and References\n"]
        lines.append(f"Generated: {citations_data.get('generated_at', 'Unknown')}\n")
        lines.append(f"Total Citations: {citations_data.get('total_citations', 0)}\n")
        lines.append(f"Used Citations: {citations_data.get('used_citations', 0)}\n\n")
        
        # Group by type
        by_type = citations_data.get('by_type', {})
        if by_type:
            lines.append("## Sources by Type\n")
            for source_type, count in by_type.items():
                if count > 0:
                    type_name = {
                        "web": "Web Articles",
                        "youtube": "YouTube Videos",
                        "arxiv": "arXiv Papers",
                        "pubmed": "PubMed Papers"
                    }.get(source_type, source_type.title())
                    lines.append(f"- {type_name}: {count}\n")
            lines.append("\n")
        
        # List all citations
        citations = citations_data.get('citations', [])
        if citations:
            lines.append("## Full Bibliography (APA Style)\n\n")
            for citation in citations:
                if citation.get('quote_count', 0) > 0:  # Only used citations
                    source_id = citation.get('source_id', 'unknown')
                    apa = citation.get('citations', {}).get('apa', 'Citation unavailable')
                    lines.append(f"**[{source_id}]** {apa}\n\n")
                    
                    # Add usage info
                    if citation.get('used_in_sections'):
                        sections = ', '.join(citation['used_in_sections'])
                        lines.append(f"   *Used in: {sections}*\n")
                    if citation.get('quote_count'):
                        lines.append(f"   *Referenced: {citation['quote_count']} time(s)*\n")
                    lines.append("\n")
        
        lines.append("\n---\n")
        lines.append(f"*Generated by AI Podcast Production Suite on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
        
        return "".join(lines)

    def _write_metadata_file(self, package_dir: str, content_package: PodcastContentPackage) -> None:
        metadata_path = os.path.join(package_dir, "metadata.json")

        # Try to get metadata as a dict from Pydantic or fallback
        meta_obj = getattr(content_package, "metadata", None)
        try:
            if hasattr(meta_obj, "model_dump"):
                meta_dict = meta_obj.model_dump()
            elif isinstance(meta_obj, dict):
                meta_dict = meta_obj
            else:
                meta_dict = model_to_dict(meta_obj) if meta_obj is not None else {}
        except Exception:
            meta_dict = {}

        # Add runtime metadata and safe fallbacks
        generated_at = meta_dict.get("generated_at", None)
        if generated_at and not isinstance(generated_at, str):
            # Convert datetime to ISO format string
            try:
                generated_at = generated_at.isoformat()
            except Exception:
                generated_at = datetime.now().isoformat()
        elif not generated_at:
            generated_at = datetime.now().isoformat()
        
        metadata = {
            "topic": meta_dict.get("topic", None),
            "refined_topic": meta_dict.get("refined_topic", None),
            "tone": meta_dict.get("tone", None),
            "estimated_duration_min": meta_dict.get("estimated_duration_min", None),
            "generated_at": generated_at,
            "word_count": meta_dict.get("word_count", 0),
            "version": meta_dict.get("version", "1.0"),
            "script_length_chars": len(getattr(content_package, "script", "") or ""),
            "show_notes_length_chars": len(getattr(content_package, "show_notes", "") or ""),
            "total_sources": len(getattr(content_package, "all_sources", []) or []),
            "social_platforms": list((model_to_dict(getattr(content_package, "social_media_posts", {})) or {}).keys()),
            "quality_score": getattr(getattr(content_package, "quality_report", None), "overall_score", None)
        }

        with open(metadata_path, 'w', encoding='utf-8') as f:
            json.dump(metadata, f, indent=2, ensure_ascii=False)

        self.logger.debug(f"Metadata written to: {metadata_path}")

    def _write_consolidated_json(self, package_dir: str, content_package: PodcastContentPackage) -> str:
        consolidated_path = os.path.join(package_dir, "podcast_package.json")

        # Convert Pydantic model to dict safely with JSON serialization mode
        package_dict = {}
        try:
            if hasattr(content_package, "model_dump"):
                # Use mode="json" to ensure datetime objects are serialized
                package_dict = content_package.model_dump(mode="json")
            else:
                package_dict = model_to_dict(content_package)
        except Exception:
            try:
                if hasattr(content_package, "dict"):
                    package_dict = content_package.dict()
                else:
                    package_dict = model_to_dict(content_package)
            except Exception:
                package_dict = {}

        # Ensure generated_at is a string
        if "generated_at" not in package_dict or not isinstance(package_dict.get("generated_at"), str):
            package_dict["generated_at"] = datetime.now().isoformat()

        with open(consolidated_path, 'w', encoding='utf-8') as f:
            json.dump(package_dict, f, indent=2, ensure_ascii=False)

        self.logger.info(f"Consolidated JSON package written to: {consolidated_path}")
        return consolidated_path

    def _sanitize_filename(self, filename: str) -> str:
        if not filename:
            filename = "untitled"
        sanitized = "".join(c if c.isalnum() or c in (' ', '-', '_') else '_' for c in filename)
        sanitized = sanitized.replace(' ', '_')[:100]
        return sanitized

    def cleanup_old_outputs(self, keep_last_n: int = 5) -> None:
        try:
            if not os.path.exists(self.base_output_dir):
                return

            dirs = [d for d in os.listdir(self.base_output_dir) if os.path.isdir(os.path.join(self.base_output_dir, d))]

            if len(dirs) <= keep_last_n:
                return

            dirs_with_time = []
            for d in dirs:
                dir_path = os.path.join(self.base_output_dir, d)
                mtime = os.path.getmtime(dir_path)
                dirs_with_time.append((mtime, d))

            dirs_with_time.sort()  # oldest first

            import shutil
            for i in range(len(dirs_with_time) - keep_last_n):
                old_dir = os.path.join(self.base_output_dir, dirs_with_time[i][1])
                shutil.rmtree(old_dir)
                self.logger.info(f"Cleaned up old output: {old_dir}")

        except Exception as e:
            self.logger.warning(f"Error during cleanup: {str(e)}")
